// Code generated by MockGen. DO NOT EDIT.
// Source: meye-core/internal/domain/campaign (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/campaign_repository_mock.go -package=mocks -mock_names=Repository=MockCampaignRepository meye-core/internal/domain/campaign Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	campaign "meye-core/internal/domain/campaign"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCampaignRepository is a mock of Repository interface.
type MockCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockCampaignRepositoryMockRecorder is the mock recorder for MockCampaignRepository.
type MockCampaignRepositoryMockRecorder struct {
	mock *MockCampaignRepository
}

// NewMockCampaignRepository creates a new mock instance.
func NewMockCampaignRepository(ctrl *gomock.Controller) *MockCampaignRepository {
	mock := &MockCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepository) EXPECT() *MockCampaignRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockCampaignRepository) FindByID(ctx context.Context, id string) (*campaign.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*campaign.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCampaignRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCampaignRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockCampaignRepository) Save(ctx context.Context, arg1 *campaign.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCampaignRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCampaignRepository)(nil).Save), ctx, arg1)
}
