// Code generated by MockGen. DO NOT EDIT.
// Source: meye-core/internal/domain/shared (interfaces: IdentificationService)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/identification_service_mock.go -package=mocks meye-core/internal/domain/shared IdentificationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentificationService is a mock of IdentificationService interface.
type MockIdentificationService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentificationServiceMockRecorder
	isgomock struct{}
}

// MockIdentificationServiceMockRecorder is the mock recorder for MockIdentificationService.
type MockIdentificationServiceMockRecorder struct {
	mock *MockIdentificationService
}

// NewMockIdentificationService creates a new mock instance.
func NewMockIdentificationService(ctrl *gomock.Controller) *MockIdentificationService {
	mock := &MockIdentificationService{ctrl: ctrl}
	mock.recorder = &MockIdentificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentificationService) EXPECT() *MockIdentificationServiceMockRecorder {
	return m.recorder
}

// GenerateID mocks base method.
func (m *MockIdentificationService) GenerateID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateID indicates an expected call of GenerateID.
func (mr *MockIdentificationServiceMockRecorder) GenerateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateID", reflect.TypeOf((*MockIdentificationService)(nil).GenerateID))
}
