// Code generated by MockGen. DO NOT EDIT.
// Source: meye-core/internal/domain/campaign (interfaces: PjRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/pj_repository_mock.go -package=mocks meye-core/internal/domain/campaign PjRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	campaign "meye-core/internal/domain/campaign"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPjRepository is a mock of PjRepository interface.
type MockPjRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPjRepositoryMockRecorder
	isgomock struct{}
}

// MockPjRepositoryMockRecorder is the mock recorder for MockPjRepository.
type MockPjRepositoryMockRecorder struct {
	mock *MockPjRepository
}

// NewMockPjRepository creates a new mock instance.
func NewMockPjRepository(ctrl *gomock.Controller) *MockPjRepository {
	mock := &MockPjRepository{ctrl: ctrl}
	mock.recorder = &MockPjRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPjRepository) EXPECT() *MockPjRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockPjRepository) FindByID(ctx context.Context, id string) (*campaign.PJ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*campaign.PJ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPjRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPjRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockPjRepository) Save(ctx context.Context, pj *campaign.PJ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, pj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPjRepositoryMockRecorder) Save(ctx, pj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPjRepository)(nil).Save), ctx, pj)
}
