// Code generated by MockGen. DO NOT EDIT.
// Source: meye-core/internal/domain/session (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/session_repository_mock.go -package=mocks -mock_names=Repository=MockSessionRepository meye-core/internal/domain/session Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	session "meye-core/internal/domain/session"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of Repository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSessionRepository) Save(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepositoryMockRecorder) Save(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepository)(nil).Save), ctx, s)
}
